config/routes.rb
Rails.application.routes.draw do
    resources :publishers do
    collection do
      get :clear
    end
  end
    resources :authors do
    collection do
      get :clear
    end
  end
  resources :books  do
    collection do
      get :clear
      get :search
      get :favorites
    end
    post 'add_to_favorites', on: :member
    post 'remove_from_favorites', on: :member
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :first_name, :last_name, :date_of_birth, presence: true

  def full_name
    "#{last_name} #{first_name}"
  end

  def age
    Date.today.year - date_of_birth.year
  end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
 before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.page(params[:page])

    # Initialize session variables if they are not set
    session[:query] ||= nil

    # Retrieve filter and search parameters from the session
    session[:query] = params[:query] if params[:query].present?

    # Filter by birth year
    if params[:date_of_birth].present?
      year = params[:date_of_birth].to_i
      start_date = Date.new(year, 1, 1)
      end_date = Date.new(year, 12, 31)
      @authors = @authors.where(date_of_birth: start_date..end_date)
    end

    # Filter by nationality
     if params[:nationality].present?
        @authors = Author.where(nationality: params[:nationality]).page(params[:page])
      end

      # Filter by author search
    if session[:query].present?
      sql_subquery = "first_name ILIKE :query OR last_name ILIKE :query"
      @authors = @authors.where(sql_subquery, query: "%#{session[:query]}%")
    else
      session[:query] = nil
    end
  end

  def clear
    session.delete(:query)
    redirect_to authors_path
  end

  # GET /authors/1
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  def destroy
    @author.destroy

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully deleted." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:first_name, :last_name, :date_of_birth, :about, :nationality)
    end

end

app/views/authors/_form.html.erb
<div class="pt-4">
  <%= simple_form_for(@author, html: { class: "row" }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :first_name, required: true %>
      <%= f.input :last_name, required: true %>
      <%= f.input :date_of_birth, required: true, as: :string, input_html: { data: { controller: "flatpickr" } }  %>
      <%= f.input :about %>
      <%= f.input :nationality, as: :country %>

    </div>

    <div class="form-actions d-flex justify-content-between">
      <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <% if !current_page?('/authors/new') %>
        <%= button_to "Delete this author", @author, method: :delete, class: "btn btn-danger text-white" %>
      <% end %>
    </div>
</div>

app/views/authors/edit.html.erb
<div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>Editing author</h1>
  <div>
  <%= link_to "Show this author", @author %> |
  <%= link_to "Back to authors", authors_path %>
  </div>
</div>


<%= render "form", author: @author %>

<br>


</div>

app/views/authors/index.html.erb
<div class="d-flex justify-content-between align-items-end">
<div class="d-flex gap-3">
<a href="/books" class="title-link"><h1>Books</h1></a>
<a href="/authors" class="title-link active"><h1>Authors</h1></a>
<a href="/publishers" class="title-link"><h1>Publishers</h1></a>
</div>
 <%= link_to new_author_path, class: "text-nowrap text-decoration-none" do%>
      <i class="fa-solid fa-plus"></i> New author
      <% end %>
</div>


<div class="d-flex my-5 align-items-center">
    <%= form_with(url: authors_path, method: :get, class: "") do |f| %>
      <%= f.text_field :query, placeholder: "Search by author", value: params[:query], class: "border border-blue-500 rounded p-2" %>

      <%= f.button "Search", value: "submit", class: "p-2" %>
    <% end %>

<%= form_with(url: authors_path, method: :get, class: "px-3", data: { controller: "filters", "filters-target": "form" } ) do |f| %>
  <%= f.select :nationality, options_for_select(Author.distinct.order(:nationality).pluck(:nationality), params[:nationality]), { include_blank: "Nationality" }, data: { action: "change->filters#submitForm" } %>
<% end %>

<%= form_with(url: authors_path, method: :get, class: "pe-3", data: { controller: "filters", "filters-target": "form" } ) do |f| %>
    <%= f.select :date_of_birth, options_for_select((1960..Date.today.year).to_a, params[:date_of_birth]), { include_blank: "Year" }, data: { action: "change->filters#submitForm" }  %>
<% end %>
<%= link_to "Reset", clear_authors_path, class: "text-nowrap text-decoration-none" %>

  </div>



<div class="table-responsive">
<table class="table table-hover align-middle">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Number of books</th>
      <th scope="col">Date of birth</th>
      <th scope="col">About</th>
      <th scope="col">Nationality</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @authors.each do |author| %>
    <tr>
      <th scope="row"><%= author.id %></th>
      <td><%= link_to "#{author.first_name} #{author.last_name}", author_path(author), class: "text-nowrap text-decoration-none" %></td>
      <td><%= author.books.count %></td>
      <td><%= author.date_of_birth %></td>
      <td><%= author.about %></td>
      <td><%= author.nationality %></td>
      <td><%= link_to edit_author_path(author), class: "text-warning text-nowrap text-decoration-none" do%>
      Edit <i class="fas fa-pencil-alt"></i>
      <% end %>
      </td>
      <td>
  <%= link_to author, class: "text-danger text-nowrap text-decoration-none", method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure? This will delete all book dependencies.' } do %>
    Delete <i class="far fa-trash-alt"></i>
  <% end %>
</td>
    </tr>
  </tbody>
  <% end %>
</table>
<div class="pagination-container">
  <%= paginate @authors %>
</div>
</div>

app/views/authors/new.html.erb
<div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>New author</h1>
  <%= link_to "Back to authors", authors_path %>
</div>

<%= render "form", author: @author %>

<br>

</div>

app/views/authors/show.html.erb
<div id="<%= dom_id @author %>">
<h1><%= "#{@author.first_name} #{@author.last_name}" %></h1>
<div class="d-flex flex-wrap gap-3 my-5">
<% @author.books.each do |book| %>
    <div class="text-center" style="width: 200px;">
    <i class="fa-solid fa-book-open fs-1 text-center pb-3"></i>
      <h5><strong><%= link_to book.title, book_path(book), class: "text-decoration-none" %></strong></h5>
      </div>
    <% end %>
</div>
</div>
<div>
  <%= link_to "Edit this author", edit_author_path(@author) %> |
  <%= link_to "Back to authors", authors_path %>
</div>