config/routes.rb
Rails.application.routes.draw do
    resources :publishers do
    collection do
      get :clear
    end
  end
    resources :authors do
    collection do
      get :clear
    end
  end
  resources :books  do
    collection do
      get :clear
      get :search
      get :favorites
    end
    post 'add_to_favorites', on: :member
    post 'remove_from_favorites', on: :member
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to :root, class: "navbar-brand ps-3" do %>
    <h1><i class="fa-solid fa-book"></i> Booky</h1>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Favorites", favorites_books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Admin Panel", books_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>