config/routes.rb
Rails.application.routes.draw do
    resources :publishers do
    collection do
      get :clear
    end
  end
    resources :authors do
    collection do
      get :clear
    end
  end
  resources :books  do
    collection do
      get :clear
      get :search
      get :favorites
    end
    post 'add_to_favorites', on: :member
    post 'remove_from_favorites', on: :member
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
before_action :set_publisher, only: %i[ show edit update destroy ]

  # GET /publishers or /publishers.json
  def index
    @publishers = Publisher.page(params[:page])

    # Initialize session variables if they are not set
    session[:query] ||= nil

    # Retrieve filter and search parameters from the session
    session[:query] = params[:query] if params[:query].present?

      # Filter by publisher search
    if session[:query].present?
      @publishers = @publishers.where("name ILIKE ?", "%#{session[:query]}%")
    else
      session[:query] = nil
    end
  end

  def clear
    session.delete(:query)
    redirect_to publishers_path
  end

  # GET /publishers/1
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  def destroy
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url, notice: "Publisher was successfully deleted." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publisher_params
      params.require(:publisher).permit(:first_name, :last_name, :date_of_birth, :about, :nationality)
    end

end

app/views/publishers/_form.html.erb
<div class="pt-4">
  <%= simple_form_for(@publisher, html: { class: "row" }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name, required: true %>

    </div>

    <div class="form-actions d-flex justify-content-between">
      <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <% if !current_page?('/publishers/new') %>
        <%= button_to "Delete this publisher", @publisher, method: :delete, class: "btn btn-danger text-white" %>
      <% end %>
    </div>
</div>

app/views/publishers/edit.html.erb
<%= turbo_frame_tag @publisher do %>
  <div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>Editing publisher</h1>
  <div>
  <%= link_to "Show this publisher", @publisher %> |
  <%= link_to "Back to publishers", publishers_path %>
  </div>
</div>


<%= render "form", publisher: @publisher %>

<br>


</div>
<% end %>

app/views/publishers/index.html.erb
<div class="d-flex justify-content-between align-items-end">
<div class="d-flex gap-3">
<a href="/books" class="title-link"><h1>Books</h1></a>
<a href="/authors" class="title-link"><h1>Authors</h1></a>
<a href="/publishers" class="title-link active"><h1>Publishers</h1></a>
</div>
 <%= link_to new_publisher_path, class: "text-nowrap text-decoration-none" do%>
      <i class="fa-solid fa-plus"></i> New publisher
      <% end %>
</div>


<div class="d-flex my-5 align-items-center">
    <%= form_with(url: publishers_path, method: :get, class: "") do |f| %>
      <%= f.text_field :query, placeholder: "Search by publisher", value: params[:query], class: "border border-blue-500 rounded p-2" %>

      <%= f.button "Search", value: "submit", class: "p-2" %>
    <% end %>

<%= link_to "Reset", clear_publishers_path, class: "text-nowrap text-decoration-none ps-3" %>

  </div>



<div class="table-responsive">
<table class="table table-hover align-middle">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Number of books</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @publishers.each do |publisher| %>
    <tr>
      <th scope="row"><%= publisher.id %></th>
      <td><%= link_to publisher.name, publisher_path(publisher), class: "text-nowrap text-decoration-none" %></td>
      <td><%= publisher.books.count %></td>
      <%= turbo_frame_tag publisher do %>
              <td><%= link_to edit_publisher_path(publisher), class: "text-warning text-nowrap text-decoration-none" do%>
      Edit <i class="fas fa-pencil-alt"></i>
      <% end %>
      <% end %>
      </td>
      <td>
  <%= link_to publisher, class: "text-danger text-nowrap text-decoration-none", method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure? This will delete all book dependencies.' } do %>
    Delete <i class="far fa-trash-alt"></i>
  <% end %>
</td>
    </tr>
  </tbody>
  <% end %>
</table>
<div class="pagination-container">
  <%= paginate @publishers %>
</div>
</div>

app/views/publishers/new.html.erb
<div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>New publisher</h1>
  <%= link_to "Back to publishers", publishers_path %>
</div>

<%= render "form", publisher: @publisher %>

<br>

</div>

app/views/publishers/show.html.erb
<div id="<%= dom_id @publisher %>">
<h1><%= @publisher.name %></h1>
<div class="d-flex flex-wrap gap-3 my-5">
<% @publisher.books.each do |book| %>
    <div class="text-center" style="width: 200px;">
    <i class="fa-solid fa-book-open fs-1 text-center pb-3"></i>
    <h5><strong><%= link_to book.title, book_path(book), class: "text-decoration-none" %></strong></h5>
    </div>
<% end %>
</div>
</div>
<div>
  <%= link_to "Edit this publisher", edit_publisher_path(@publisher) %> |
  <%= link_to "Back to publishers", publishers_path %>
</div>