config/routes.rb
Rails.application.routes.draw do
    resources :publishers do
    collection do
      get :clear
    end
  end
    resources :authors do
    collection do
      get :clear
    end
  end
  resources :books  do
    collection do
      get :clear
      get :search
      get :favorites
    end
    post 'add_to_favorites', on: :member
    post 'remove_from_favorites', on: :member
  end
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
  acts_as_favoritable
  validates :title, :isbn, :date_of_publication, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  include Pundit
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show, :search]

  # GET /books or /books.json
  def index
    @books = Book.page(params[:page])
    authorize @books

    # Initialize session variables if they are not set
    session[:query] ||= nil

    # Retrieve filter and search parameters from the session
    session[:query] = params[:query] if params[:query].present?

    # Filter by publication year
    if params[:date_of_publication].present?
      year = params[:date_of_publication].to_i
      start_date = Date.new(year, 1, 1)
      end_date = Date.new(year, 12, 31)
      @books = @books.where(date_of_publication: start_date..end_date)
    end

    # Filter by publisher
     if params[:publisher].present?
        publisher = Publisher.find(params[:publisher])
        @books = publisher.books.page(params[:page])
      end

      # Filter by title or author search
    if session[:query].present?
      sql_subquery = "title ILIKE :query OR authors.first_name ILIKE :query OR authors.last_name ILIKE :query"
      @books = @books.joins(:author).where(sql_subquery, query: "%#{session[:query]}%")
    else
      session[:query] = nil
    end
      rescue Pundit::NotAuthorizedError
      flash[:alert] = "You are not authorized to perform this action."
      redirect_to root_path
  end

  def clear
    session.delete(:query)
    redirect_to books_path
  end

  def search
    @books = Book.page(params[:page]).per(24)
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR authors.first_name ILIKE :query OR authors.last_name ILIKE :query"
      @books = @books.joins(:author).where(sql_subquery, query: "%#{params[:query]}%")
    else
      params[:query] = nil
  end
end

# Favorites, create controller?

def favorites
    @user = current_user
    @favorite_books = @user.all_favorites.page(params[:page])
end

  def add_to_favorites
    @book = Book.find(params[:id])
    current_user.favorite(@book)
    flash[:notice] = 'Book added to favorites successfully'
    redirect_to book_path(@book)
  end

  def remove_from_favorites
    @book = Book.find(params[:id])
    current_user.unfavorite(@book)
    flash[:notice] = 'Book removed from favorites successfully'
    redirect_to favorites_books_path
  end

  # GET /books/1 or /books/1.json
  def show
    @user = current_user
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :isbn, :date_of_publication, :review, :price, :author_id, :publisher_id)
    end

end

app/views/books/_form.html.erb
<div class="pt-4">
  <%= simple_form_for(@book, html: { class: "row" }) do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :title, class: "col", required: true %>
      <%= f.input :isbn, class: "col", required: true %>
      <%= f.input :date_of_publication, required: true, as: :string, input_html: { data: { controller: "flatpickr" } }  %>
      <%= f.input :review %>
      <%= f.input :price %>
      <%= f.association :author, label_method: :full_name, collection: Author.order(:last_name, :first_name), include_blank: "Select an Author" %>
      <%= f.association :publisher, collection: Publisher.order(:name), include_blank: "Select a Publisher" %>

    </div>

    <div class="form-actions d-flex justify-content-between">
      <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>
  <% if !current_page?('/books/new') %>
        <%= button_to "Delete this book", @book, method: :delete, class: "btn btn-danger text-white" %>
      <% end %>
    </div>
</div>

app/views/books/edit.html.erb
<div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>Editing book</h1>
  <div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
  </div>
</div>


<%= render "form", book: @book %>

<br>


</div>

app/views/books/favorites.html.erb
    <div class="d-flex flex-wrap gap-3 ">
    <% if @user.all_favorites.present? %>
    <% @user.all_favorites.each do |favorite| %>
    <div class="text-center" style="width: 200px;">
    <i class="fa-solid fa-book-open fs-1 text-center pb-3"></i>
      <h5><strong><%= link_to favorite.favoritable.title, book_path(favorite.favoritable), class: "text-decoration-none" %></strong></h5>
      <%= link_to 'Remove', remove_from_favorites_book_path(favorite.favoritable), data: { turbo_method: :post }, class: "text-danger text-decoration-none" %>
    </div>
  <% end %>
  <% else %>
    <p>No favorites yet</p>
    <% end %>
  </div>
<div class="pagination-container">
  <% paginate @favorite_books %>
</div>

app/views/books/index.html.erb
<div class="d-flex justify-content-between align-items-end">
<div class="d-flex gap-3">
<a href="/books" class="title-link active"><h1>Books</h1></a>
<a href="/authors" class="title-link"><h1>Authors</h1></a>
<a href="/publishers" class="title-link"><h1>Publishers</h1></a>
</div>
 <%= link_to new_book_path, class: "text-nowrap text-decoration-none" do%>
      <i class="fa-solid fa-plus"></i> New book
      <% end %>
</div>


<div class="d-flex my-5 align-items-center">
    <%= form_with(url: books_path, method: :get, class: "") do |f| %>
      <%= f.text_field :query, placeholder: "Search by title or author", value: params[:query], class: "border border-blue-500 rounded p-2" %>

      <%= f.button "Search", value: "submit", class: "p-2" %>
    <% end %>

<%= form_with(url: books_path, method: :get, class: "px-3", data: { controller: "filters", "filters-target": "form" } ) do |f| %>
  <%= f.select :publisher, options_for_select(Publisher.order(:name).pluck(:name, :id), params[:publisher]), { include_blank: "Publisher" }, data: { action: "change->filters#submitForm" } %>
<% end %>



<%= form_with(url: books_path, method: :get, class: "pe-3", data: { controller: "filters", "filters-target": "form" } ) do |f| %>
    <%= f.select :date_of_publication, options_for_select((1960..Date.today.year).to_a, params[:date_of_publication]), { include_blank: "Year" }, data: { action: "change->filters#submitForm" }  %>
<% end %>
<%= link_to "Reset", clear_books_path, class: "text-nowrap text-decoration-none" %>

  </div>



<div class="table-responsive">
<table class="table table-hover align-middle">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">ISBN</th>
      <th scope="col">Date of publication</th>
      <th scope="col">Review</th>
      <th scope="col">Price</th>
      <th scope="col">Author</th>
      <th scope="col">Publisher</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
      <th scope="row"><%= book.id %></th>
      <td><%= book.title %></td>
      <td class="text-nowrap"><%= book.isbn %></td>
      <td><%= book.date_of_publication %></td>
      <td><%= book.review %></td>
      <td><%= book.price %></td>
      <td><%= "#{book.author.first_name} #{book.author.last_name}" %><br><%= "(#{book.author.age})" %></td>
      <td><%= book.publisher.name %></td>
      <td><%= link_to edit_book_path(book), class: "text-warning text-nowrap text-decoration-none" do%>
      Edit <i class="fas fa-pencil-alt"></i>
      <% end %>
      </td>
      <td>
  <%= link_to book, class: "text-danger text-nowrap text-decoration-none", method: :delete, data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure?' } do %>
    Delete <i class="far fa-trash-alt"></i>
  <% end %>
</td>
    </tr>
  </tbody>
  <% end %>
</table>
<div class="pagination-container">
  <%= paginate @books %>
</div>
</div>

app/views/books/new.html.erb
<div class="mx-auto" style="width: 40%">
<div class="d-flex justify-content-between align-items-center">
  <h1>New book</h1>
  <%= link_to "Back to books", books_path %>
</div>

<%= render "form", book: @book %>

<br>

</div>

app/views/books/search.html.erb
    <div class="d-flex flex-wrap gap-3 ">
    <% if @books.present? %>
    <% @books.each do |book| %>
    <div class="text-center" style="width: 200px;">
    <i class="fa-solid fa-book-open fs-1 text-center pb-3"></i>
      <h5><strong><%= link_to book.title, book_path(book), class: "text-decoration-none" %></strong></h5>
      <p><%= "#{book.author.first_name} #{book.author.last_name}" %></p>
    </div>
  <% end %>
  <% else %>
    <p>No books found</p>
    <% end %>
  </div>
<div class="pagination-container">
  <%= paginate @books %>
</div>

app/views/books/show.html.erb
<div id="<%= dom_id @book %>">
<div class="d-flex justify-content-center align-content-center gap-5">
  <div>
    <i class="fa-solid fa-book-open text-center py-5" style="font-size: 10em"></i>
</div>
<div>
  <p>
    <h1><%= @book.title %></h1>
  </p>

    <p>
    <%= "#{@book.author.first_name} #{@book.author.last_name}" %>
  </p>

  <p>
    <strong>Isbn:</strong>
    <%= @book.isbn %>
  </p>

  <p>
    <strong>Date of publication:</strong>
    <%= @book.date_of_publication %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= @book.review %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @book.price %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= @book.publisher.name %>
  </p>
</div>
<%= link_to 'Add to Favorites', add_to_favorites_book_path(@book), data: { turbo_method: :post } %>

</div>
<div class="mt-5">
  <% if current_user && current_user.admin? %>
    <%= link_to "Edit this book", edit_book_path(@book) %> |
  <% end %>
  <%= link_to "Back", :back %>
</div>